CREATE TABLE "visits" (
	"id" serial PRIMARY KEY NOT NULL,
	"ip_address" varchar(45) NOT NULL,
	"city" varchar(100),
	"region" varchar(100),
	"region_code" varchar(10),
	"country" varchar(100),
	"country_code" varchar(5),
	"zip_code" varchar(20),
	"latitude" numeric(10, 7),
	"longitude" numeric(10, 7),
	"gps_latitude" numeric(10, 7),
	"gps_longitude" numeric(10, 7),
	"gps_accuracy" numeric(10, 2),
	"gps_city" varchar(100),
	"gps_region" varchar(100),
	"gps_region_code" varchar(10),
	"gps_country" varchar(100),
	"gps_country_code" varchar(5),
	"gps_zip_code" varchar(20),
	"gps_street_address" varchar(255),
	"gps_permission_status" varchar(20),
	"gps_error_message" text,
	"location_distance" numeric(10, 2),
	"timezone" varchar(50),
	"isp" varchar(255),
	"org" varchar(255),
	"as_number" varchar(255),
	"user_agent" text,
	"visited_at" timestamp with time zone DEFAULT now() NOT NULL
);
